## Tensors
- essentially a vector
- can have any number of dimensions
- "A tensor is a generalization of vectors and matrices to potentially higher dimensions"
- Each tensor represents a partially defined computation that will eventually produce a value
- each tensor has a datatype and shape

In [10]:
import tensorflow as tf

- scalar tensors: only 1 value
- rank = degree: number of dimensions in the tensor
- scalar tensors have rank 0
- tensor with single array have rank 1
- tensor with array of arrays have rank 2

In [11]:
rank0_tensor = tf.Variable("a", tf.string)
rank1_tensor = tf.Variable(["a", "b"], tf.string)
rank2_tensor = tf.Variable([["a","b"],["c","d"]], tf.string)


- rank is deepest level of nested list
- rank 2 called matrix/matrices

In [12]:
tf.rank(rank0_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [13]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [9]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [14]:
rank2_tensor.shape

TensorShape([2, 2])

shape [2, 2]: 2 elements in first dimension, 2 elements in second dimension

In [20]:
rank1_tensor.shape

TensorShape([2])

### Changing Shape
- many different shapes that can represent the same number of elements
- can reshape data for same amount of elements but in different shape
- ex, can put a 3x3 into a 1x9
- number of elements is product of each element of the shape

In [25]:
tensor1 = tf.ones([1,2,3]) # create shape [1,2,3] of ones
print(tensor1) # 1 interior list, 2 lists within that, 3 elements within those lists, 6 total
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2) # 2 interior lists, 3 lists within that, 1 elements within those list
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells tf to calculate the size of the dimension in that place
                                       # will reshape to [3, 2]
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Types
    - Variable: mutable
    - Constant: immutable
    - Placeholder: wont discuss much
    - SparseTensor: wont discuss much
- all immutable except for variable

### Evaluating Tensors
- create a session
- sometimes we have to evaluate the tensor to do something else

```
with tf.Session() as sess:
    tensor1.eval()
```